
spring:
# DB接続設定
  datasource:
    url: jdbc:h2:C:/data/demodb
    username: sa
    password: 
    #url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
 
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:/static/original/
        - file:/static/thumbnail/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#doma:
#  dialect: H2Dialect
#  data-source-name: ds
#  naming: SNAKE_UPPER_CASE
#  query-timeout: 30
  mail:
    host: smtp.gmail.com
    port: 587
    # あなたのGMailのアドレス
    username: buripanda@gmail.com
    # アプリ パスワード
    password: fwwahswzyrabyvae
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
server:
  port: 8080
  servlet:
    session:
      timeout: 18000
      persistent: true #再起動してもセッションが切れない

content:
  image:
    pathroot: C:\data\images\