--ユーザ情報テーブル
CREATE TABLE IF NOT EXISTS T_USER (
  ID INT NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  E_MAIL VARCHAR(100) NOT NULL,
  SEX VARCHAR(1) NOT NULL,
  IMAGE_PATH VARCHAR(50),
  TITLE VARCHAR(50),
  PRICE INT DEFAULT 0,
  AMOUNT INT DEFAULT 0,  
  RATE DECIMAL DEFAULT 0,
  RATE_SUM INT DEFAULT 0,
  ORDER_SUM INT DEFAULT 0,
  RATE_BUY DECIMAL DEFAULT 0,
  RATE_SUM_BUY INT DEFAULT 0,
  ORDER_SUM_BUY INT DEFAULT 0,
  RECOMMENT_URL1 VARCHAR(200),
  RECOMMENT_URL2 VARCHAR(200),
  RECOMMENT_URL3 VARCHAR(200),
  INSTA_URL VARCHAR(200),
  TWITTER_URL VARCHAR(200),
  YOUTUBE_URL VARCHAR(200),
  TIKTOK_URL VARCHAR(200),
  ONLINE_STATUS INT DEFAULT 0,
  REGIST_STATUS INT DEFAULT 0,
  COOKIE VARCHAR(70),
  BELL_TUCHI INT DEFAULT 0,
  CHAT_TUCHI INT DEFAULT 0,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_USER_01 ON T_USER (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_USER_02 ON T_USER (E_MAIL);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_USER_03 ON T_USER (COOKIE);

--自己紹介テーブル
CREATE TABLE IF NOT EXISTS T_USER_INTRODUCTION (
  ID INT NOT NULL,
  MESSAGE VARCHAR(2000),
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);

--メッセージ履歴テーブル
CREATE TABLE IF NOT EXISTS T_MESSAGE_HIST (
  SEND_ID INT NOT NULL,
  RECEIVE_ID INT NOT NULL,
  MESSAGE VARCHAR(400),
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_MESSAGE_HIST ON T_MESSAGE_HIST (SEND_ID, RECEIVE_ID, REGIST_DATE);

--メッセージユーザーテーブル
CREATE TABLE IF NOT EXISTS T_MESSAGE_USER (
  ID INT NOT NULL,
  PARTNER_ID INT NOT NULL,
  LAST_MESSAGE VARCHAR(400),
  HIDDEN_STATUS INT DEFAULT 0,
  NEW_MESSAGE INT DEFAULT 0,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_MESSAGE_USER ON T_MESSAGE_USER (ID, PARTNER_ID);

--購入履歴テーブル
CREATE TABLE IF NOT EXISTS T_PURCHASE_HIST (
  PURCHASE_ID INT DEFAULT 0 NOT NULL,
  BUYER_ID INT DEFAULT 0 NOT NULL,
  SELLER_ID INT DEFAULT 0 NOT NULL,
  PURCHASE_DATE TIMESTAMP NOT NULL,
  PURCHASE_KBN INT DEFAULT 0 NOT NULL,
  QUANTITY INT DEFAULT 0,
  AMOUNT INT DEFAULT 0,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (PURCHASE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_T_PURCHASE_HIST_01 ON T_PURCHASE_HIST (BUYER_ID);
CREATE INDEX IF NOT EXISTS IDX_T_PURCHASE_HIST_02 ON T_PURCHASE_HIST (SELLER_ID);

--予約履歴テーブル
CREATE TABLE IF NOT EXISTS T_RESERVE_HIST (
  RESERVE_ID INT DEFAULT 0 NOT NULL,
  BUYER_ID INT DEFAULT 0 NOT NULL,
  SELLER_ID INT DEFAULT 0 NOT NULL,
  QUANTITY INT DEFAULT 0 NOT NULL,
  PRICE INT DEFAULT 0 NOT NULL,
  AMOUNT INT DEFAULT 0 ,
  RESERVE_START_DATE TIMESTAMP NOT NULL,
  RESERVE_END_DATE TIMESTAMP,
  BUYER_COMMENT VARCHAR(400),
  BUYER_RATE DECIMAL DEFAULT 0,
  BUYER_FLG INT DEFAULT 0,
  SELLER_COMMENT VARCHAR(400),
  SELLER_RATE DECIMAL DEFAULT 0 ,
  SELLER_FLG INT DEFAULT 0,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (RESERVE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_T_RESERVE_HIST_01 ON T_RESERVE_HIST (BUYER_ID);
CREATE INDEX IF NOT EXISTS IDX_T_RESERVE_HIST_02 ON T_RESERVE_HIST (SELLER_ID);

--課金履歴テーブル
CREATE TABLE IF NOT EXISTS T_CHARGE_HIST (
  CHARGE_ID INT DEFAULT 0 NOT NULL,
  FROM_ID INT DEFAULT 0 NOT NULL,
  TO_ID INT DEFAULT 0 NOT NULL,
  CHARGE_DATE TIMESTAMP NOT NULL,
  CHARGE_KBN INT DEFAULT 0 NOT NULL,
  QUANTITY INT DEFAULT 0,
  AMOUNT INT DEFAULT 0,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (CHARGE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_T_CHARGE_HIST_01 ON T_CHARGE_HIST (FROM_ID);
CREATE INDEX IF NOT EXISTS IDX_T_CHARGE_HIST_02 ON T_CHARGE_HIST (TO_ID);

--募集テーブル
CREATE TABLE IF NOT EXISTS T_RECRUIT (
  RECRUIT_ID INT DEFAULT 0 NOT NULL,
  ID INT DEFAULT 0 NOT NULL,
  RECRUIT_START_DATE TIMESTAMP NOT NULL,
  RECRUIT_END_DATE TIMESTAMP NOT NULL,
  MESSAGE VARCHAR(200),
  STOP_FLG INT DEFAULT 0 NOT NULL,
  NOW_FLG INT DEFAULT 0 NOT NULL,
  RECRUIT_FLG INT DEFAULT 0 NOT NULL,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (RECRUIT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_T_RECRUIT ON T_RECRUIT (ID);

--売上テーブル
CREATE TABLE IF NOT EXISTS T_SALES (
  ID INT DEFAULT 0 NOT NULL,
  SALES_SUM INT DEFAULT 0, -- 売上金額
  SALES_CASH_SUM INT DEFAULT 0,  -- 振込依頼金額
  NAME_SEI VARCHAR(20),
  NAME_MEI VARCHAR(20),
  NAME_SEI_KANA VARCHAR(40),
  NAME_MEI_KANA VARCHAR(40),
  BANK_NAME VARCHAR(40),
  BANK_BRANCH_CD VARCHAR(6),
  BANK_KND INT DEFAULT 0,
  KOZA_NO VARCHAR(10),
  KOZA_NAME VARCHAR(60),
  SALES_CASH_STATUS INT DEFAULT 0, -- 0:振込依頼なし　1:振込完了　2:振込依頼中
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);

--売上履歴テーブル
CREATE TABLE IF NOT EXISTS T_SALES_HIST (
  SALES_ID INT DEFAULT 0 NOT NULL,
  ID INT DEFAULT 0 NOT NULL,
  FROM_ID INT DEFAULT 0 NOT NULL,
  SALES_DATE TIMESTAMP NOT NULL,
  SALES_KBN INT DEFAULT 0, -- 1:チケット購入 2:スパチャ 3:ギフト 4:コイン購入
  SALES_CONTENT VARCHAR(200),
  AMOUNT INT DEFAULT 0 NOT NULL,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (SALES_ID)
);
CREATE INDEX IF NOT EXISTS IDX_T_SALES_HIST_01 ON T_SALES_HIST (ID);

--シーケンス
CREATE SEQUENCE IF NOT EXISTS "USER_ID_SEQ";
CREATE SEQUENCE IF NOT EXISTS "PURCHASE_ID_SEQ";
CREATE SEQUENCE IF NOT EXISTS "RESERVE_ID_SEQ";
CREATE SEQUENCE IF NOT EXISTS "CHARGE_ID_SEQ";
CREATE SEQUENCE IF NOT EXISTS "RECRUIT_ID_SEQ";
CREATE SEQUENCE IF NOT EXISTS "SALES_ID_SEQ";
