--ユーザ情報テーブル
CREATE TABLE IF NOT EXISTS T_USER (
  ID INT NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  E_MAIL VARCHAR(100) NOT NULL,
  SEX VARCHAR(1) NOT NULL,
  IMAGE_PATH VARCHAR(50),
  TITLE VARCHAR(50),
  MESSAGE VARCHAR(400),
  TANKA INT DEFAULT 0,
  EVALUATION DECIMAL DEFAULT 0,
  ORDER_SUM INT DEFAULT 0,
  INSTA_URL VARCHAR(200),
  TWITTER_URL VARCHAR(200),
  YOUTUBE_URL VARCHAR(200),
  TIKTOK_URL VARCHAR(200),
  ONLINE_STATUS INT DEFAULT 0,
  REGIST_STATUS INT DEFAULT 0,
  COOKIE VARCHAR(70),
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_USER_01 ON T_USER (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_USER_02 ON T_USER (E_MAIL);


--メッセージ履歴テーブル
CREATE TABLE IF NOT EXISTS T_MESSAGE_HIST (
  SEND_ID INT NOT NULL,
  RECEIVE_ID INT NOT NULL,
  MESSAGE VARCHAR(400),
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_MESSAGE_HIST ON T_MESSAGE_HIST (SEND_ID, RECEIVE_ID, REGIST_DATE);

--メッセージユーザーテーブル
CREATE TABLE IF NOT EXISTS T_MESSAGE_USER (
  ID INT NOT NULL,
  PARTNER_ID INT NOT NULL,
  LAST_MESSAGE VARCHAR(400),
  HIDDEN_STATUS INT DEFAULT 0,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_MESSAGE_USER ON T_MESSAGE_USER (ID, PARTNER_ID);

--購入履歴テーブル
CREATE TABLE IF NOT EXISTS T_PURCHASE_HIST (
  TICKET_ID INT NOT NULL,
  SELLER_ID VARCHAR(20) NOT NULL,
  BUYER_ID VARCHAR(20) NOT NULL,
  BUY_DATE TIMESTAMP NOT NULL,
  BUY_NUM INT NOT NULL,
  START_BUY_DATE TIMESTAMP NOT NULL,
  END_BUY_DATE TIMESTAMP NOT NULL,
  SELLER_EVALUATION DECIMAL,
  BUYER_EVALUATION DECIMAL,
  SELLER_COMMENT VARCHAR(400),
  BUYER_COMMENT VARCHAR(400),
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (TICKET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_T_PURCHASE_HIST ON T_PURCHASE_HIST (SELLER_ID);
CREATE INDEX IF NOT EXISTS IDX_T_PURCHASE_HIST ON T_PURCHASE_HIST (BUYER_ID);

--シーケンス
CREATE SEQUENCE IF NOT EXISTS "USER_ID_SEQ";
CREATE SEQUENCE IF NOT EXISTS "TICKET_ID_SEQ";
