--ユーザ情報テーブル
CREATE TABLE IF NOT EXISTS T_USER (
  ID INT NOT NULL,
  USER_ID VARCHAR(20) NOT NULL,
  USER_NAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(20) NOT NULL,
  E_MAIL VARCHAR(100) NOT NULL,
  SEX VARCHAR(1) NOT NULL,
  IMAGE_PATH VARCHAR(50),
  TITLE VARCHAR(50),
  MESSAGE VARCHAR(400),
  COST INT DEFAULT 0,
  AMOUNT INT DEFAULT 0,  
  RATE DECIMAL DEFAULT 0,
  ORDER_SUM INT DEFAULT 0,
  INSTA_URL VARCHAR(200),
  TWITTER_URL VARCHAR(200),
  YOUTUBE_URL VARCHAR(200),
  TIKTOK_URL VARCHAR(200),
  ONLINE_STATUS INT DEFAULT 0,
  REGIST_STATUS INT DEFAULT 0,
  COOKIE VARCHAR(70),
  BELL_TUCHI INT DEFAULT 0,
  CHAT_TUCHI INT DEFAULT 0,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_USER_01 ON T_USER (USER_ID);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_USER_02 ON T_USER (E_MAIL);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_USER_03 ON T_USER (COOKIE);


--メッセージ履歴テーブル
CREATE TABLE IF NOT EXISTS T_MESSAGE_HIST (
  SEND_ID INT NOT NULL,
  RECEIVE_ID INT NOT NULL,
  MESSAGE VARCHAR(400),
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_MESSAGE_HIST ON T_MESSAGE_HIST (SEND_ID, RECEIVE_ID, REGIST_DATE);

--メッセージユーザーテーブル
CREATE TABLE IF NOT EXISTS T_MESSAGE_USER (
  ID INT NOT NULL,
  PARTNER_ID INT NOT NULL,
  LAST_MESSAGE VARCHAR(400),
  HIDDEN_STATUS INT DEFAULT 0,
  NEW_MESSAGE INT DEFAULT 0,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_T_MESSAGE_USER ON T_MESSAGE_USER (ID, PARTNER_ID);

--購入履歴テーブル
CREATE TABLE IF NOT EXISTS T_PURCHASE_HIST (
  PURCHASE_ID INT DEFAULT 0 NOT NULL,
  BUYER_ID INT DEFAULT 0 NOT NULL,
  SELLER_ID INT DEFAULT 0 NOT NULL,
  PURCHASE_DATE TIMESTAMP NOT NULL,
  PURCHASE_KBN INT DEFAULT 0 NOT NULL,
  QUANTITY INT DEFAULT 0,
  AMOUNT INT DEFAULT 0,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (PURCHASE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_T_PURCHASE_HIST ON T_PURCHASE_HIST (BUYER_ID);
CREATE INDEX IF NOT EXISTS IDX_T_PURCHASE_HIST ON T_PURCHASE_HIST (SELLER_ID);

--予約履歴テーブル
CREATE TABLE IF NOT EXISTS T_RESERVE_HIST (
  RESERVE_ID INT DEFAULT 0 NOT NULL,
  BUYER_ID INT DEFAULT 0 NOT NULL,
  SELLER_ID INT DEFAULT 0 NOT NULL,
  QUANTITY INT DEFAULT 0 NOT NULL,
  COST INT DEFAULT 0 NOT NULL,
  AMOUNT INT DEFAULT 0 ,
  RESERVE_START_DATE TIMESTAMP NOT NULL,
  RESERVE_END_DATE TIMESTAMP,
  BUYER_COMMENT VARCHAR(400),
  BUYER_RATE DECIMAL DEFAULT 0 ,
  SELLER_COMMENT VARCHAR(400),
  SELLER_RATE DECIMAL DEFAULT 0 ,
  DELETE_FLG CHAR(1) DEFAULT 0 NOT NULL,
  REGIST_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (RESERVE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_T_RESERVE_HIST ON T_RESERVE_HIST (BUYER_ID);
CREATE INDEX IF NOT EXISTS IDX_T_RESERVE_HIST ON T_RESERVE_HIST (SELLER_ID);

--シーケンス
CREATE SEQUENCE IF NOT EXISTS "USER_ID_SEQ";
CREATE SEQUENCE IF NOT EXISTS "PURCHASE_ID_SEQ";
CREATE SEQUENCE IF NOT EXISTS "RESERVE_ID_SEQ";
